### PR TITLE
#99 Improved Trainee Profile

### LINKED ISSUE #99: Improve Profile
Improve the functionality and layout of the edit buttons on the profile page for consistency.

1. The button should redirect to the edit profile
2. Another one should redirect to  profile image edit
3. When there's no profile image use a substring of both names as a profile placeholder but It does not work for android only iOS. We need it to work on both platforms.

### PR DESCRIPTION
**Pull request by munezeromicha**
### What does this PR do?

This PR implements profile avatar management functionality in the trainee profile section, allowing users to update their profile pictures through the mobile device's media library. The implementation includes image picker integration with Expo, proper permission handling, and GraphQL mutation for avatar updates. The feature provides real-time feedback through toast notifications and automatically refreshes the UI upon successful updates. The avatar editing interface is seamlessly integrated into the existing profile page with a clean, user-friendly design that maintains consistency with the app's styling.

- Implements avatar update functionality in the trainee profile section
- Adds image picker integration using expo-image-picker
- Implements GraphQL mutation for avatar updates
- Adds immediate UI feedback through toast notifications
- Handles permission requests for accessing device media library
- Implements automatic profile refresh after avatar update

### How should this be manually tested?
1. Navigate to the trainee profile page
2. Click on the "Edit" button next to the profile avatar
3. Verify that the app requests permission to access the media library
4. Select an image from the device gallery
5. Verify that:
   - A loading state is shown during upload
   - A success toast appears after successful upload
   - The profile avatar updates immediately
   - The image appears correctly cropped in 1:1 aspect ratio
6. Test error scenarios:
   - Deny permission and verify appropriate error message
   - Cancel image selection
   - Test with offline connection

### ScreenShoots:

<div style="display: flex; flex-wrap: wrap;">
    Screenshot 1
    Screenshot 1
</div>

### CODE REVIEW

**Review by pacifiquemboni — APPROVED** [review]

**Review by MugemaneBertin2001 — APPROVED** [review]

**Review by Christian-Ishimwe — APPROVED** [review]

**Comment by ncutixavier** [comment]
I still see two edit button

image

**Comment by munezeromicha** [comment]
> I still see two edit button
> 
> image

@ncutixavier as you see we have two edit button which are working different, one button is for editing profile image of trainee and the second is for editing the trainee profile data like firstname, secondname and others....

**Review by niyibi250 — COMMENTED** [review]
image
can you change this if possible

**Review by niyibi250 — APPROVED** [review]

**Review by pacifiquemboni — COMMENTED** [review]
Good work @munezeromicha

**Review by ncutixavier — APPROVED** [review]

**Pull request merged**
